services:
  alloy:
    image: grafana/alloy:v1.13.2
    container_name: alloy
    command: run /etc/alloy/config.alloy
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    restart: unless-stopped
    cpus: "0.2"
    mem_limit: "256m"